# Generated by Django 6.1 on 2026-08-29 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('file_name', models.CharField(max_length=255)),
                ('resume_text', models.TextField(blank=True)),
                ('score', models.IntegerField(default=0)),
                ('score_label', models.CharField(blank=True, max_length=50)),
                ('domain', models.CharField(blank=True, max_length=50)),
                ('strengths', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('found_skills', models.JSONField(default=list)),
                ('word_count', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
